name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable]
        experimental: [false]
        include:
          # smoketests for future and experimental toolchains
          - {toolchain: stable, os: windows-latest, experimental: false}
          - {toolchain: stable, os: macos-latest, experimental: false}
          - {toolchain: beta, os: ubuntu-latest, experimental: false}
          - {toolchain: nightly, os: ubuntu-latest, experimental: true}
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{matrix.toolchain}}
        override: true
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all
    - name: Check Examples
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --examples
    - name: Run Example - Hello Warc
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --example hello_warc
